version: "3.8"
services:
  minic2:
    build: .
    environment:
      MINIC2_PORT: /dev/ttyACM1
      MINIC2_CHANNEL: 1
      MINIC2_TIMEOUT: 20
    devices:
      - /dev/ttyACM1:/dev/ttyACM1
    restart: unless-stopped
